<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $now = Carbon::now();
        $tickets = [
            [
                'namaTiket' => 'Konser Jazz Night',
                'harga' => 250000.00,
                'stok' => 150,
                'lokawebsi' => 'Gedung Kesenian Jakarta, Jl. Gedung Kesenian No.1',
                'gambar' => 'jazz_night.jpg',
                'deskripsi' => 'Konser jazz malam hari dengan musisi ternama Indonesia',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-15',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-15',
                'waktu_mulai' => '19:00:00',
                'waktu_selesai' => '23:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Festival Kuliner Bandung',
                'harga' => 75000.00,
                'stok' => 300,
                'lokawebsi' => 'Lapangan Gasibu, Bandung',
                'gambar' => 'food_festival.jpg',
                'deskripsi' => 'Festival makanan dengan berbagai kuliner khas Bandung',
                'regencie_id' => '3273',
                'tanggal_pelaksanaan' => '2023-11-25',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-11-27',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '22:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pameran Teknologi',
                'harga' => 120000.00,
                'stok' => 0,
                'lokawebsi' => 'Jakarta Convention Center',
                'gambar' => 'tech_expo.jpg',
                'deskripsi' => 'Pameran teknologi terbaru dari berbagai perusahaan IT',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-10-10',
                'status' => 'tidak tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-10-12',
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '17:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Workshop Fotografi',
                'harga' => 350000.00,
                'stok' => 25,
                'lokawebsi' => 'KreativHub, Surabaya',
                'gambar' => 'photography_workshop.jpg',
                'deskripsi' => 'Workshop fotografi profesional dengan fotografer ternama',
                'regencie_id' => '3578',
                'tanggal_pelaksanaan' => '2023-12-05',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-05',
                'waktu_mulai' => '13:00:00',
                'waktu_selesai' => '17:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Konser Dangdut',
                'harga' => 150000.00,
                'stok' => 200,
                'lokawebsi' => 'Lapangan Karebosi, Makassar',
                'gambar' => 'dangdut_concert.jpg',
                'deskripsi' => 'Konser dangdut dengan artis papan atas Indonesia',
                'regencie_id' => '7371',
                'tanggal_pelaksanaan' => '2024-01-20',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2024-01-20',
                'waktu_mulai' => '20:00:00',
                'waktu_selesai' => '02:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Seminar Kewirausahaan',
                'harga' => 100000.00,
                'stok' => 80,
                'lokawebsi' => 'Universitas Gadjah Mada, Yogyakarta',
                'gambar' => 'entrepreneur_seminar.jpg',
                'deskripsi' => 'Seminar tentang kewirausahaan dengan pembicara sukses',
                'regencie_id' => '3471',
                'tanggal_pelaksanaan' => '2023-11-15',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-11-15',
                'waktu_mulai' => '08:30:00',
                'waktu_selesai' => '15:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pertunjukan Teater',
                'harga' => 120000.00,
                'stok' => 50,
                'lokawebsi' => 'Teater Kecil, Taman Ismail Marzuki',
                'gambar' => 'theater_show.jpg',
                'deskripsi' => 'Pertunjukan teater modern dengan aktor ternama',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-22',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-24',
                'waktu_mulai' => '19:30:00',
                'waktu_selesai' => '21:30:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Festival Lampion',
                'harga' => 50000.00,
                'stok' => 0,
                'lokawebsi' => 'Taman Mini Indonesia Indah',
                'gambar' => 'lantern_festival.jpg',
                'deskripsi' => 'Festival lampion dengan berbagai pertunjukan budaya',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-11-30',
                'status' => 'tidak tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-02',
                'waktu_mulai' => '18:00:00',
                'waktu_selesai' => '23:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Marathon Kota Lama',
                'harga' => 175000.00,
                'stok' => 120,
                'lokawebsi' => 'Kawasan Kota Lama, Semarang',
                'gambar' => 'marathon.jpg',
                'deskripsi' => 'Lari marathon menyusuri kawasan bersejarah Kota Lama',
                'regencie_id' => '3374',
                'tanggal_pelaksanaan' => '2024-02-18',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2024-02-18',
                'waktu_mulai' => '05:00:00',
                'waktu_selesai' => '10:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pameran Seni Rupa',
                'harga' => 80000.00,
                'stok' => 40,
                'lokawebsi' => 'Galeri Nasional Indonesia',
                'gambar' => 'art_exhibition.jpg',
                'deskripsi' => 'Pameran karya seni rupa kontemporer Indonesia',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-10',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-20',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '18:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pertunjukan Teater',
                'harga' => 120000.00,
                'stok' => 50,
                'lokawebsi' => 'Teater Kecil, Taman Ismail Marzuki',
                'gambar' => 'theater_show.jpg',
                'deskripsi' => 'Pertunjukan teater modern dengan aktor ternama',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-22',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-24',
                'waktu_mulai' => '19:30:00',
                'waktu_selesai' => '21:30:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Festival Lampion',
                'harga' => 50000.00,
                'stok' => 0,
                'lokawebsi' => 'Taman Mini Indonesia Indah',
                'gambar' => 'lantern_festival.jpg',
                'deskripsi' => 'Festival lampion dengan berbagai pertunjukan budaya',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-11-30',
                'status' => 'tidak tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-02',
                'waktu_mulai' => '18:00:00',
                'waktu_selesai' => '23:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Marathon Kota Lama',
                'harga' => 175000.00,
                'stok' => 120,
                'lokawebsi' => 'Kawasan Kota Lama, Semarang',
                'gambar' => 'marathon.jpg',
                'deskripsi' => 'Lari marathon menyusuri kawasan bersejarah Kota Lama',
                'regencie_id' => '3374',
                'tanggal_pelaksanaan' => '2024-02-18',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2024-02-18',
                'waktu_mulai' => '05:00:00',
                'waktu_selesai' => '10:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pameran Seni Rupa',
                'harga' => 80000.00,
                'stok' => 40,
                'lokawebsi' => 'Galeri Nasional Indonesia',
                'gambar' => 'art_exhibition.jpg',
                'deskripsi' => 'Pameran karya seni rupa kontemporer Indonesia',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-10',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-20',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '18:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pertunjukan Teater',
                'harga' => 120000.00,
                'stok' => 50,
                'lokawebsi' => 'Teater Kecil, Taman Ismail Marzuki',
                'gambar' => 'theater_show.jpg',
                'deskripsi' => 'Pertunjukan teater modern dengan aktor ternama',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-22',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-24',
                'waktu_mulai' => '19:30:00',
                'waktu_selesai' => '21:30:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Festival Lampion',
                'harga' => 50000.00,
                'stok' => 0,
                'lokawebsi' => 'Taman Mini Indonesia Indah',
                'gambar' => 'lantern_festival.jpg',
                'deskripsi' => 'Festival lampion dengan berbagai pertunjukan budaya',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-11-30',
                'status' => 'tidak tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-02',
                'waktu_mulai' => '18:00:00',
                'waktu_selesai' => '23:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Marathon Kota Lama',
                'harga' => 175000.00,
                'stok' => 120,
                'lokawebsi' => 'Kawasan Kota Lama, Semarang',
                'gambar' => 'marathon.jpg',
                'deskripsi' => 'Lari marathon menyusuri kawasan bersejarah Kota Lama',
                'regencie_id' => '3374',
                'tanggal_pelaksanaan' => '2024-02-18',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2024-02-18',
                'waktu_mulai' => '05:00:00',
                'waktu_selesai' => '10:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pameran Seni Rupa',
                'harga' => 80000.00,
                'stok' => 40,
                'lokawebsi' => 'Galeri Nasional Indonesia',
                'gambar' => 'art_exhibition.jpg',
                'deskripsi' => 'Pameran karya seni rupa kontemporer Indonesia',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-10',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-20',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '18:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pertunjukan Teater',
                'harga' => 120000.00,
                'stok' => 50,
                'lokawebsi' => 'Teater Kecil, Taman Ismail Marzuki',
                'gambar' => 'theater_show.jpg',
                'deskripsi' => 'Pertunjukan teater modern dengan aktor ternama',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-22',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-24',
                'waktu_mulai' => '19:30:00',
                'waktu_selesai' => '21:30:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Festival Lampion',
                'harga' => 50000.00,
                'stok' => 0,
                'lokawebsi' => 'Taman Mini Indonesia Indah',
                'gambar' => 'lantern_festival.jpg',
                'deskripsi' => 'Festival lampion dengan berbagai pertunjukan budaya',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-11-30',
                'status' => 'tidak tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-02',
                'waktu_mulai' => '18:00:00',
                'waktu_selesai' => '23:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Marathon Kota Lama',
                'harga' => 175000.00,
                'stok' => 120,
                'lokawebsi' => 'Kawasan Kota Lama, Semarang',
                'gambar' => 'marathon.jpg',
                'deskripsi' => 'Lari marathon menyusuri kawasan bersejarah Kota Lama',
                'regencie_id' => '3374',
                'tanggal_pelaksanaan' => '2024-02-18',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2024-02-18',
                'waktu_mulai' => '05:00:00',
                'waktu_selesai' => '10:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pameran Seni Rupa',
                'harga' => 80000.00,
                'stok' => 40,
                'lokawebsi' => 'Galeri Nasional Indonesia',
                'gambar' => 'art_exhibition.jpg',
                'deskripsi' => 'Pameran karya seni rupa kontemporer Indonesia',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-10',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-20',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '18:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pertunjukan Teater',
                'harga' => 120000.00,
                'stok' => 50,
                'lokawebsi' => 'Teater Kecil, Taman Ismail Marzuki',
                'gambar' => 'theater_show.jpg',
                'deskripsi' => 'Pertunjukan teater modern dengan aktor ternama',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-22',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-24',
                'waktu_mulai' => '19:30:00',
                'waktu_selesai' => '21:30:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Festival Lampion',
                'harga' => 50000.00,
                'stok' => 0,
                'lokawebsi' => 'Taman Mini Indonesia Indah',
                'gambar' => 'lantern_festival.jpg',
                'deskripsi' => 'Festival lampion dengan berbagai pertunjukan budaya',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-11-30',
                'status' => 'tidak tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-02',
                'waktu_mulai' => '18:00:00',
                'waktu_selesai' => '23:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Marathon Kota Lama',
                'harga' => 175000.00,
                'stok' => 120,
                'lokawebsi' => 'Kawasan Kota Lama, Semarang',
                'gambar' => 'marathon.jpg',
                'deskripsi' => 'Lari marathon menyusuri kawasan bersejarah Kota Lama',
                'regencie_id' => '3374',
                'tanggal_pelaksanaan' => '2024-02-18',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2024-02-18',
                'waktu_mulai' => '05:00:00',
                'waktu_selesai' => '10:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pameran Seni Rupa',
                'harga' => 80000.00,
                'stok' => 40,
                'lokawebsi' => 'Galeri Nasional Indonesia',
                'gambar' => 'art_exhibition.jpg',
                'deskripsi' => 'Pameran karya seni rupa kontemporer Indonesia',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-10',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-20',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '18:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pertunjukan Teater',
                'harga' => 120000.00,
                'stok' => 50,
                'lokawebsi' => 'Teater Kecil, Taman Ismail Marzuki',
                'gambar' => 'theater_show.jpg',
                'deskripsi' => 'Pertunjukan teater modern dengan aktor ternama',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-22',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-24',
                'waktu_mulai' => '19:30:00',
                'waktu_selesai' => '21:30:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Festival Lampion',
                'harga' => 50000.00,
                'stok' => 0,
                'lokawebsi' => 'Taman Mini Indonesia Indah',
                'gambar' => 'lantern_festival.jpg',
                'deskripsi' => 'Festival lampion dengan berbagai pertunjukan budaya',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-11-30',
                'status' => 'tidak tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-02',
                'waktu_mulai' => '18:00:00',
                'waktu_selesai' => '23:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Marathon Kota Lama',
                'harga' => 175000.00,
                'stok' => 120,
                'lokawebsi' => 'Kawasan Kota Lama, Semarang',
                'gambar' => 'marathon.jpg',
                'deskripsi' => 'Lari marathon menyusuri kawasan bersejarah Kota Lama',
                'regencie_id' => '3374',
                'tanggal_pelaksanaan' => '2024-02-18',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2024-02-18',
                'waktu_mulai' => '05:00:00',
                'waktu_selesai' => '10:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pameran Seni Rupa',
                'harga' => 80000.00,
                'stok' => 40,
                'lokawebsi' => 'Galeri Nasional Indonesia',
                'gambar' => 'art_exhibition.jpg',
                'deskripsi' => 'Pameran karya seni rupa kontemporer Indonesia',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-10',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-20',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '18:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pertunjukan Teater',
                'harga' => 120000.00,
                'stok' => 50,
                'lokawebsi' => 'Teater Kecil, Taman Ismail Marzuki',
                'gambar' => 'theater_show.jpg',
                'deskripsi' => 'Pertunjukan teater modern dengan aktor ternama',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-22',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-24',
                'waktu_mulai' => '19:30:00',
                'waktu_selesai' => '21:30:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Festival Lampion',
                'harga' => 50000.00,
                'stok' => 0,
                'lokawebsi' => 'Taman Mini Indonesia Indah',
                'gambar' => 'lantern_festival.jpg',
                'deskripsi' => 'Festival lampion dengan berbagai pertunjukan budaya',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-11-30',
                'status' => 'tidak tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-02',
                'waktu_mulai' => '18:00:00',
                'waktu_selesai' => '23:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Marathon Kota Lama',
                'harga' => 175000.00,
                'stok' => 120,
                'lokawebsi' => 'Kawasan Kota Lama, Semarang',
                'gambar' => 'marathon.jpg',
                'deskripsi' => 'Lari marathon menyusuri kawasan bersejarah Kota Lama',
                'regencie_id' => '3374',
                'tanggal_pelaksanaan' => '2024-02-18',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2024-02-18',
                'waktu_mulai' => '05:00:00',
                'waktu_selesai' => '10:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pameran Seni Rupa',
                'harga' => 80000.00,
                'stok' => 40,
                'lokawebsi' => 'Galeri Nasional Indonesia',
                'gambar' => 'art_exhibition.jpg',
                'deskripsi' => 'Pameran karya seni rupa kontemporer Indonesia',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-10',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-20',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '18:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pertunjukan Teater',
                'harga' => 120000.00,
                'stok' => 50,
                'lokawebsi' => 'Teater Kecil, Taman Ismail Marzuki',
                'gambar' => 'theater_show.jpg',
                'deskripsi' => 'Pertunjukan teater modern dengan aktor ternama',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-22',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-24',
                'waktu_mulai' => '19:30:00',
                'waktu_selesai' => '21:30:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Festival Lampion',
                'harga' => 50000.00,
                'stok' => 0,
                'lokawebsi' => 'Taman Mini Indonesia Indah',
                'gambar' => 'lantern_festival.jpg',
                'deskripsi' => 'Festival lampion dengan berbagai pertunjukan budaya',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-11-30',
                'status' => 'tidak tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-02',
                'waktu_mulai' => '18:00:00',
                'waktu_selesai' => '23:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Marathon Kota Lama',
                'harga' => 175000.00,
                'stok' => 120,
                'lokawebsi' => 'Kawasan Kota Lama, Semarang',
                'gambar' => 'marathon.jpg',
                'deskripsi' => 'Lari marathon menyusuri kawasan bersejarah Kota Lama',
                'regencie_id' => '3374',
                'tanggal_pelaksanaan' => '2024-02-18',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2024-02-18',
                'waktu_mulai' => '05:00:00',
                'waktu_selesai' => '10:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pameran Seni Rupa',
                'harga' => 80000.00,
                'stok' => 40,
                'lokawebsi' => 'Galeri Nasional Indonesia',
                'gambar' => 'art_exhibition.jpg',
                'deskripsi' => 'Pameran karya seni rupa kontemporer Indonesia',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-10',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-20',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '18:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pertunjukan Teater',
                'harga' => 120000.00,
                'stok' => 50,
                'lokawebsi' => 'Teater Kecil, Taman Ismail Marzuki',
                'gambar' => 'theater_show.jpg',
                'deskripsi' => 'Pertunjukan teater modern dengan aktor ternama',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-22',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-24',
                'waktu_mulai' => '19:30:00',
                'waktu_selesai' => '21:30:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Festival Lampion',
                'harga' => 50000.00,
                'stok' => 0,
                'lokawebsi' => 'Taman Mini Indonesia Indah',
                'gambar' => 'lantern_festival.jpg',
                'deskripsi' => 'Festival lampion dengan berbagai pertunjukan budaya',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-11-30',
                'status' => 'tidak tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-02',
                'waktu_mulai' => '18:00:00',
                'waktu_selesai' => '23:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Marathon Kota Lama',
                'harga' => 175000.00,
                'stok' => 120,
                'lokawebsi' => 'Kawasan Kota Lama, Semarang',
                'gambar' => 'marathon.jpg',
                'deskripsi' => 'Lari marathon menyusuri kawasan bersejarah Kota Lama',
                'regencie_id' => '3374',
                'tanggal_pelaksanaan' => '2024-02-18',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2024-02-18',
                'waktu_mulai' => '05:00:00',
                'waktu_selesai' => '10:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'namaTiket' => 'Pameran Seni Rupa',
                'harga' => 80000.00,
                'stok' => 40,
                'lokawebsi' => 'Galeri Nasional Indonesia',
                'gambar' => 'art_exhibition.jpg',
                'deskripsi' => 'Pameran karya seni rupa kontemporer Indonesia',
                'regencie_id' => '3171',
                'tanggal_pelaksanaan' => '2023-12-10',
                'status' => 'tersedia',
                'tanggal_selesai_pelaksanaan' => '2023-12-20',
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '18:00:00',
                'created_at' => $now,
                'updated_at' => $now
            ]
        ];

        DB::table('tikets')->insert($tickets);
    }
}
